WIP feature/paging
Lightmatter/welkin-health pull request #23
Opened 2022-07-28 17:17 UTC by alonzopt

Still a little messy/light on comments but passes read-all tests for users, patients, and calendar events.

Had to move base `PageIterator` class above `Collection` in `models/base.py` to make vscode respect the reference.

`PageableIterator` and `MetaInfoIterator` are for existing the paging types, `MetaIterator` is for chat. Class names are from their key in the response, very willing to change them.

Will need to rebase for CDT stuff, but at a glance the 4th paging style should be pretty easy to make a Iterator class for.

2022-07-28 19:29 UTC, alonzopt commented
> What's the purpose behind the getter/setter methods here? Also, if we do need to use getters/setter methods, I'd suggest using this pattern:
> 
> ```python
> @property
> def foo(self):
>     return self._foo
> 
> @foo.setter
> def foo(self, value):
>     self._foo = value
> ```

`_set_last` can be changed to a setter since that's going to be universal (at least for the 4 types we have now).`_set_page` is a little more complicated since the token based pagination (`MetaIterator`) doesn't use pages so that needed to be broken out. It might just be easier to merge the functions into something named like `_update_self_after_request(meta)` and the subclasses can do whatever they need in that.

The get methods can probably just be moved to variables, I had started with the sets and was probably overthinking the design and trying to keep that stuff hidden when it doesn't need to be.

2022-08-02 19:44 UTC, alonzopt commented
Code coverage dropping is due to the inclusion of the pagination class for chat. Did not want to comment out a class for something that will be in use soon.

2022-08-04 17:03 UTC, samamorgan requested changes
Great work! Have a few changes commented. Feel free to push back.

2022-08-04 17:03 UTC, samamorgan commented on welkin/models/pagination.py
> +    def __init__(self, collection, resource, method, size=20, *args, **kwargs):
No need to have all of the arguments listed in these subclasses. You can just do:

```python
def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    ...
```

2022-08-04 17:03 UTC, samamorgan commented on welkin/models/pagination.py
> +            "pageSize": 20,
Should this be `"pageSize": self.size`?

2022-08-05 19:48 UTC, alonzopt commented
All suggestions were good and have been implemented.

Reminder the test coverage drops because chat pagination class is included in the pagination file.
Test coverage passes in chat PR https://github.com/Lightmatter/welkin-health/pull/26

2022-08-08 14:39 UTC, samamorgan approved these changes
LGTM!

2022-08-08 15:40 UTC, merged