Feature/chat
Lightmatter/welkin-health pull request #26
Opened 2022-08-02 19:49 UTC by alonzopt

Chat resources and collections, plus tests.
This is a branch off of feature/paging and so can be merged instead or will be updated after feature/paging is merged.

2022-08-04 18:31 UTC, samamorgan commented
@alonzopt I'll wait to review this one until feature/paging is merged.

2022-08-09 00:29 UTC, samamorgan requested changes
Just a few changes needed. I think some restructuring of `MetaIterator` might be required. I'm hoping we didn't lose intended functionality in #23

2022-08-09 00:29 UTC, samamorgan commented on welkin/models/chat.py
> +        pageSize: int = 20,
These arguments don't follow [PEP8 conventions](https://peps.python.org/pep-0008/#function-and-method-arguments) (should be snake_case).

The only time we should be using lowerCamelCase is when we're interacting with data that was parsed from a request (like `Encounter().patientId`). If it's purely python functionality, snake_case is correct (like `Encounter().get(patient_id="")`.

2022-08-09 00:29 UTC, samamorgan commented on welkin/models/chat.py
> +            params["pageToken"] = pageToken
Pagination parameters should be handled by the underlying paginator class. A user should be able to pass `paginate=True` and `size=int` to any paginated collection get method, those would pass to the request method through args/kwargs, and that in turn passes to the paginator class.

2022-08-09 00:29 UTC, samamorgan commented on welkin/models/chat.py
> +            "pageSize": pageSize,
Same comment here as above on pagination handling

2022-08-09 19:09 UTC, alonzopt commented
Requested changes complete. Got the variables renamed and moved code out of Chat Collections and into the MetaIterator

2022-08-09 23:58 UTC, samamorgan approved these changes
LGTM! I'm going to add a quick line to one of the tests to check the string representation of a chat so we cover that line.

2022-08-09 23:58 UTC, samamorgan commented on welkin/models/chat.py
> +        content_page_size: int = 20,
So chat search has an additional parameter for controlling pagination? Very similar to the token-based pagination, but one additional parameter? That's the 5th scheme. Silly.

2022-08-10 01:15 UTC, merged