Feature/care plan
Lightmatter/welkin-health pull request #33
Opened 2022-08-10 18:57 UTC by alonzopt

Adding `CarePlan` model with tests.

Updating was a bit of an issue since the endpoint is `PUT` but will only accept the key `"overview"` which is found in `CarePlan.patientOverview["overview"]` from the `GET` response.

Implemented update via subresource pattern established by `Assessments` to resolve this.

The subresource `Goal` and it's subresources will be implemented in a future PR.

2022-08-10 20:40 UTC, samamorgan requested changes

2022-08-10 22:31 UTC, edcohen08 approved these changes
LGTM with Sam's changes. My only nit would be to have the Care Plan create in the CarePlanOverview rather than CarePlan because it hits. a /overview endpoint

2022-08-12 15:46 UTC, alonzopt commented
Added ability to pass patient id to class methods.

Also made a util function to traverse parents looking for patient id. In addition to its current use, it will be needed goals which are subresources in CarePlans and then goals will have subresources as well. I think its workable but I feel like there's some room for improvement that I'm missing despite it staring me in the face.

2022-08-12 16:05 UTC, samamorgan approved these changes
LGTM! There may be a simple way to scan through the tree for patient ID, but I couldn't think of anything better at a quick glance, and working is better than perfect. We can refine after we're out of alpha.

2022-08-12 16:10 UTC, merged